#!/usr/bin/env bash
# rpow2 — one-command local dev bootstrap.
#
# Usage:
#   ./up.sh                  # bring everything up with sane defaults
#   ./up.sh --rebuild        # force a clean rebuild of dev images + npm install
#   ./up.sh --down           # tear the stack down (keep volumes)
#   ./up.sh --wipe           # tear the stack down AND wipe all volumes
#
# Override host ports by exporting before running:
#   RPOW_API_PORT=9000 RPOW_WEB_PORT=9001 RPOW_DB_PORT=9002 ./up.sh
#
# Per-user secrets (Solana RPC, bridge keypair, etc.) belong in the
# gitignored docker/dev.env.local — see docker/README.md.
set -euo pipefail
cd "$(dirname "$0")"

# ---- output helpers ----------------------------------------------------------
if [ -t 1 ] && [ -z "${NO_COLOR-}" ]; then
  C_DIM=$'\033[2m'; C_OK=$'\033[1;32m'; C_WARN=$'\033[1;33m'
  C_ERR=$'\033[1;31m'; C_HDR=$'\033[1;36m'; C_OFF=$'\033[0m'
else
  C_DIM=; C_OK=; C_WARN=; C_ERR=; C_HDR=; C_OFF=
fi
say()  { printf '%s\n' "${C_DIM}[*]${C_OFF} $*"; }
ok()   { printf '%s\n' "${C_OK}[+]${C_OFF} $*"; }
warn() { printf '%s\n' "${C_WARN}[!]${C_OFF} $*"; }
err()  { printf '%s\n' "${C_ERR}[x]${C_OFF} $*" >&2; }

# ---- subcommands -------------------------------------------------------------
case "${1-}" in
  ""|--up) ;;
  --down)
    say "tearing the stack down (volumes preserved)..."
    docker compose down
    ok "down"
    exit 0
    ;;
  --wipe)
    warn "wiping the stack including all volumes (db, node_modules, signing keys)..."
    docker compose down -v
    rm -f .env
    ok "wiped"
    exit 0
    ;;
  --rebuild)
    say "forcing a clean rebuild..."
    docker compose down
    docker compose build --no-cache
    # Force reinstall of npm deps + workspace builds on next up.
    docker volume rm rpow2-dev_rpow-node-modules >/dev/null 2>&1 || true
    ;;
  -h|--help)
    sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
  *)
    err "unknown flag: $1"
    err "run './up.sh --help' for usage"
    exit 1
    ;;
esac

cat <<'BANNER'

+======================================================================+
|                   rpow2 - local dev bootstrap                        |
+======================================================================+
BANNER

# ---- pre-flight --------------------------------------------------------------
say "checking docker..."
command -v docker >/dev/null 2>&1 \
  || { err "docker not found. install Docker Desktop or Engine: https://docs.docker.com/get-docker/"; exit 1; }
ok "docker $(docker --version | awk '{print $3}' | tr -d ,)"

say "checking docker compose v2..."
docker compose version >/dev/null 2>&1 \
  || { err "'docker compose' v2 not found. update Docker, or install the compose plugin."; exit 1; }
ok "compose $(docker compose version --short)"

say "checking docker daemon..."
docker info >/dev/null 2>&1 \
  || { err "cannot reach docker daemon. start Docker Desktop, or 'sudo systemctl start docker'."; exit 1; }
ok "daemon reachable"

# ---- port detection ----------------------------------------------------------
# Walks forward from each default until it finds a free host port. Uses
# bash's /dev/tcp magic so there are no external deps (`lsof`, `nc`, etc.).

is_port_free() {
  ! (echo > "/dev/tcp/127.0.0.1/$1") 2>/dev/null
}
next_free_port() {
  local p=$1 tries=30
  while [ $tries -gt 0 ]; do
    if is_port_free "$p"; then echo "$p"; return 0; fi
    p=$((p + 1)); tries=$((tries - 1))
  done
  return 1
}

DEFAULT_API=8080; DEFAULT_WEB=5173; DEFAULT_DB=55432
say "picking host ports..."
API_PORT=${RPOW_API_PORT:-$(next_free_port $DEFAULT_API || echo "")}
WEB_PORT=${RPOW_WEB_PORT:-$(next_free_port $DEFAULT_WEB || echo "")}
DB_PORT=${RPOW_DB_PORT:-$(next_free_port  $DEFAULT_DB  || echo "")}
[ -n "$API_PORT" ] && [ -n "$WEB_PORT" ] && [ -n "$DB_PORT" ] \
  || { err "no free host ports near $DEFAULT_API/$DEFAULT_WEB/$DEFAULT_DB"; exit 1; }

if [ "$API_PORT" = "$DEFAULT_API" ] && [ "$WEB_PORT" = "$DEFAULT_WEB" ] && [ "$DB_PORT" = "$DEFAULT_DB" ]; then
  ok "ports $API_PORT / $WEB_PORT / $DB_PORT (defaults, all free)"
else
  warn "default ports busy; using $API_PORT / $WEB_PORT / $DB_PORT instead"
fi

# ---- write .env for compose interpolation -----------------------------------
cat > .env <<EOF
# Auto-generated by ./up.sh — safe to delete; will be regenerated on next run.
# Override by exporting RPOW_*_PORT before ./up.sh, or by editing this file.
# Application secrets (Solana RPC, bridge keypair) belong in docker/dev.env.local.
RPOW_API_PORT=$API_PORT
RPOW_WEB_PORT=$WEB_PORT
RPOW_DB_PORT=$DB_PORT
RPOW_API_BASE_URL=http://localhost:$API_PORT
RPOW_WEB_BASE_URL=http://localhost:$WEB_PORT
EOF

# ---- start the stack ---------------------------------------------------------
say "starting the stack (first run pulls images + npm installs; ~2 min — subsequent runs are quick)..."
docker compose up -d --build --remove-orphans 2>&1 | sed 's/^/    /'

# ---- wait for /health --------------------------------------------------------
say "waiting for the api on :$API_PORT..."
deadline=$((SECONDS + 300))
while :; do
  if curl -fsS "http://localhost:$API_PORT/health" >/dev/null 2>&1; then
    ok "api responding to /health"
    break
  fi
  if [ $SECONDS -ge $deadline ]; then
    err "/health did not respond within 5 minutes."
    err "last 30 server log lines:"
    docker compose logs --tail=30 server 2>&1 | sed 's/^/    /' || true
    exit 1
  fi
  sleep 1
done

# ---- friendly banner ---------------------------------------------------------
WEB_URL="http://localhost:$WEB_PORT"
API_URL="http://localhost:$API_PORT"
DB_URL="postgres://rpow:rpow_dev@localhost:$DB_PORT/rpow"

cat <<EOF

  ${C_HDR}WEB${C_OFF}    : $WEB_URL
  ${C_HDR}API${C_OFF}    : $API_URL
  ${C_HDR}DB${C_OFF}     : $DB_URL
  PUBKEY : $API_URL/.well-known/rpow-pubkey.pem

  sign in        : open $WEB_URL/#/login → "Create new wallet"
                   the browser holds your private key; the server only sees
                   your public key + per-action Ed25519 signatures
  watch logs     : docker compose logs -f server
  stop           : ./up.sh --down
  full reset     : ./up.sh --wipe

EOF
